stages:
  - format
  - build
  - test
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  GIT_SUBMODULE_STRATEGY: normal

build:
  stage: build
  script:
    RUST_BACKTRACE=1 cargo build

format:
  stage: test
  script:
    cargo fmt --all -- --check
  allow_failure: true

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose -- --test-threads=1

pages:
  stage: deploy
  only:
    - master
  script:
    - cargo doc
    - rm -rf public
    - mv target/doc/ public
  artifacts:
    paths:
      - public

cache:
  paths:
    - dynamorio/
    - cargo/
    - target/
