stages:
  - format
  - build
  - test
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  GIT_SUBMODULE_STRATEGY: normal

default-build:
  stage: build
  script:
    RUST_BACKTRACE=1 cargo build

dynamorio-build:
  stage: build
  script:
    RUST_BACKTRACE=1 cargo build --features "dynamorio"

format:
  stage: test
  script:
    cargo fmt --all -- --check

default-test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose -- --test-threads=1

dynamorio-test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --features "dynamorio" -- --test-threads=1

pages:
  stage: deploy
  only:
    - master
  script:
    - cargo doc --all-features
    - rm -rf public
    - mv target/doc/ public
  artifacts:
    paths:
      - public

cache:
  paths:
    - dynamorio/
    - build_32/
    - build_64/
    - cargo/
    - target/
